#!/usr/bin/bash
if [ "EUID" -ne 0 ]; then
    echo "Error: Please run this script as root or with sudo to see the process names."
    exit 1
fi

echo "Displaying listening ports with PID and program Name:"
echo "-------------------------------------------------------"

ss -tulnp
