#!/usr/bin/env bash
# Rewrites /etc/hosts so localhost and facebook.com point to new addresses
grep -v -E '(^| )(localhost|facebook\.com)($| )' /etc/hosts > /tmp/hosts.new
echo "127.0.0.2 localhost" >> /tmp/hosts.new
echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
cat /tmp/hosts.new > /etc/hosts
