#!/usr/bin/env bash
# Rewrites /etc/hosts so localhost and facebook.com point to new addresses
sed -i '/localhost/d; /facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
